# Generated by Django 4.1.7 on 2023-04-20 14:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import image_cropping.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(max_length=200)),
                ('holder_name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Payment',
                'verbose_name_plural': 'Card Payments',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='ChildDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_gender', models.CharField(max_length=50)),
                ('child_date_of_birth', models.DateField()),
                ('date_of_dedication', models.DateField()),
                ('mothers_name', models.CharField(max_length=200)),
                ('mothers_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fathers_name', models.CharField(max_length=200)),
                ('fathers_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dedication_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('feature_img', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='feature_img/')),
                ('cropping', image_cropping.fields.ImageRatioField('feature_img', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('commence_date', models.DateTimeField(blank=True, null=True)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MpesaPayment',
                'verbose_name_plural': 'MpesaPayments',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='NewBeleiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('current_church', models.CharField(max_length=200)),
                ('residential_area', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('prayer_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('feature_img', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='feature_img/')),
                ('cropping', image_cropping.fields.ImageRatioField('feature_img', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('preacher', models.CharField(max_length=50)),
                ('readings', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
