# Generated by Django 4.1.7 on 2023-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_remove_sermon_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='feature_img/'),
        ),
    ]
