# Generated by Django 4.1.7 on 2023-06-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_sermon_feature_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='event',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='feature_img/'),
        ),
    ]
