# Generated by Django 4.1.7 on 2023-03-30 08:53

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('feature_img', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
