# Generated by Django 4.1.7 on 2023-04-06 09:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_gender', models.CharField(max_length=50)),
                ('child_date_of_birth', models.DateField()),
                ('date_of_dedication', models.DateField()),
                ('mothers_name', models.CharField(max_length=200)),
                ('mothers_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fathers_name', models.CharField(max_length=200)),
                ('fathers_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dedication_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewBeleiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('current_church', models.CharField(max_length=200)),
                ('residential_area', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('prayer_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
