# Generated by Django 4.1.7 on 2023-04-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='reference',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='organization_balance',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='type',
        ),
    ]
