# Generated by Django 4.1.7 on 2023-04-11 12:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_rename_reference_mpesapayment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('braintree_id', models.CharField(max_length=200)),
                ('holder_name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Payment',
                'verbose_name_plural': 'Card Payments',
            },
        ),
    ]
